// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NurseryLink.Infrastructure.Data;

#nullable disable

namespace NurseryLink.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260825130524_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NurseryLink.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AccountType");

                    b.HasIndex("IsSeeded")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_OnlyOneSeededAdmin")
                        .HasFilter("[IsSeeded] = 1");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_SeededAccountStaysActive", "[IsSeeded] = 0 OR [IsActive] = 1");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LoggedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LoggedByAccountId");

                    b.HasIndex("ClassId", "LocalDate");

                    b.HasIndex("StudentId", "LocalDate", "LogType");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.AdminPrivilege", b =>
                {
                    b.Property<Guid>("AdminAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Privilege")
                        .HasColumnType("int");

                    b.HasKey("AdminAccountId", "Privilege");

                    b.ToTable("AdminPrivileges", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("AdminAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdminAccountId");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ClassTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("int");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClassTeachers_OneCurrentPermanentTeacherPerClass")
                        .HasFilter("[EndedAtUtc] IS NULL AND [AssignmentType] = 0");

                    b.HasIndex("ClassId", "EndedAtUtc");

                    b.HasIndex("TeacherAccountId", "EndedAtUtc");

                    b.ToTable("ClassTeachers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ClassTeachers_EndsAfterStart", "[EndedAtUtc] IS NULL OR [EndedAtUtc] > [StartedAtUtc]");
                        });
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("Type");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ParentNotification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationId", "ParentAccountId");

                    b.HasIndex("IsRead");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("ParentNotifications", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ParentStudent", b =>
                {
                    b.Property<Guid>("ParentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ParentAccountId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentStudents", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AccountId", "RevokedAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentClassId");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("NurseryLink.Domain.Entities.Account");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CreatedByAdminId");

                    b.ToTable("Admins", null, t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_SeededAccountStaysActive", "[IsSeeded] = 0 OR [IsActive] = 1");
                        });
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Parent", b =>
                {
                    b.HasBaseType("NurseryLink.Domain.Entities.Account");

                    b.ToTable("Parents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_SeededAccountStaysActive", "[IsSeeded] = 0 OR [IsActive] = 1");
                        });
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Teacher", b =>
                {
                    b.HasBaseType("NurseryLink.Domain.Entities.Account");

                    b.ToTable("Teachers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_SeededAccountStaysActive", "[IsSeeded] = 0 OR [IsActive] = 1");
                        });
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Class", "Class")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Account", "LoggedByAccount")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("LoggedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Student", "Student")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("LoggedByAccount");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.AdminPrivilege", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Admin", "AdminAccount")
                        .WithMany("Privileges")
                        .HasForeignKey("AdminAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Admin", "AdminAccount")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ClassTeacher", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Class", "Class")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Teacher", "TeacherAccount")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("TeacherAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Student", "Student")
                        .WithMany("Notifications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ParentNotification", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Notification", "Notification")
                        .WithMany("ParentNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Parent", "ParentAccount")
                        .WithMany("Notifications")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ParentStudent", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Parent", "ParentAccount")
                        .WithMany("ParentStudents")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Student", "Student")
                        .WithMany("ParentStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentAccount");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Student", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("CurrentClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Admin", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Admin", "CreatedByAdmin")
                        .WithMany("CreatedAdmins")
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NurseryLink.Domain.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("NurseryLink.Domain.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Parent", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("NurseryLink.Domain.Entities.Parent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("NurseryLink.Domain.Entities.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Account", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Class", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("ClassTeachers");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Notification", b =>
                {
                    b.Navigation("ParentNotifications");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Student", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Notifications");

                    b.Navigation("ParentStudents");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Admin", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedAdmins");

                    b.Navigation("Privileges");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Parent", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ParentStudents");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("ClassTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
