// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NurseryLink.Infrastructure.Data;

#nullable disable

namespace NurseryLink.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816110930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NurseryLink.Domain.Entities.AdminPrivilege", b =>
                {
                    b.Property<id>("AdminAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Privilege")
                        .HasColumnType("int");

                    b.HasKey("AdminAccountId", "Privilege");

                    b.ToTable("AdminPrivileges", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.AuditLog", b =>
                {
                    b.Property<id>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<id>("AdminAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdminAccountId");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Class", b =>
                {
                    b.Property<id>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<id>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TeacherAccountId");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.MealEntry", b =>
                {
                    b.Property<id>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<id>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EatingStatus")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<id>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<id>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherAccountId");

                    b.HasIndex("StudentId", "MealType", "LocalDate")
                        .IsUnique();

                    b.ToTable("MealEntries", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Notification", b =>
                {
                    b.Property<id>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<id>("ParentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<id>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.HasIndex("ParentAccountId");

                    b.HasIndex("StudentId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ParentStudent", b =>
                {
                    b.Property<id>("ParentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<id>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ParentAccountId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentStudents", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Student", b =>
                {
                    b.Property<id>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<id>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.TemperatureReading", b =>
                {
                    b.Property<id>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<id>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<id>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<id>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValueCelsius")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherAccountId");

                    b.ToTable("TemperatureReadings", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ToiletVisit", b =>
                {
                    b.Property<id>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<id>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<id>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<id>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VisitType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherAccountId");

                    b.ToTable("ToiletVisits", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Account", b =>
                {
                    b.Property<id>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<id?>("CreatedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");



                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.AdminPrivilege", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Account", "AdminAccount")
                        .WithMany("Privileges")
                        .HasForeignKey("AdminAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Account", "AdminAccount")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Class", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Account", "TeacherAccount")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeacherAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.MealEntry", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Class", "Class")
                        .WithMany("MealEntries")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Student", "Student")
                        .WithMany("MealEntries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Account", "TeacherAccount")
                        .WithMany("MealEntries")
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("TeacherAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Account", "ParentAccount")
                        .WithMany("Notifications")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Student", "Student")
                        .WithMany("Notifications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentAccount");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ParentStudent", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Account", "ParentAccount")
                        .WithMany("ParentStudents")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Student", "Student")
                        .WithMany("ParentStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentAccount");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Student", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.TemperatureReading", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Class", "Class")
                        .WithMany("TemperatureReadings")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Student", "Student")
                        .WithMany("TemperatureReadings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Account", "TeacherAccount")
                        .WithMany("TemperatureReadings")
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("TeacherAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.ToiletVisit", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Class", "Class")
                        .WithMany("ToiletVisits")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Student", "Student")
                        .WithMany("ToiletVisits")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NurseryLink.Domain.Entities.Account", "TeacherAccount")
                        .WithMany("ToiletVisits")
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("TeacherAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Account", b =>
                {
                    b.HasOne("NurseryLink.Domain.Entities.Account", "CreatedByAccount")
                        .WithMany("CreatedAccounts")
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByAccount");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Class", b =>
                {
                    b.Navigation("MealEntries");

                    b.Navigation("Students");

                    b.Navigation("TemperatureReadings");

                    b.Navigation("ToiletVisits");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Student", b =>
                {
                    b.Navigation("MealEntries");

                    b.Navigation("Notifications");

                    b.Navigation("ParentStudents");

                    b.Navigation("TemperatureReadings");

                    b.Navigation("ToiletVisits");
                });

            modelBuilder.Entity("NurseryLink.Domain.Entities.Account", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Classes");

                    b.Navigation("CreatedAccounts");

                    b.Navigation("MealEntries");

                    b.Navigation("Notifications");

                    b.Navigation("ParentStudents");

                    b.Navigation("Privileges");

                    b.Navigation("TemperatureReadings");

                    b.Navigation("ToiletVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
